Server:
  SystemName: "example_pine_cluster"
  ID: connector-0 # 唯一ID
  Kind: connector # 服务器类型
  Host: 127.0.0.1 
  Port: 3014 
  IsConnector: true
  Token: ksYNdrAo # 集群认证Token
  LogType: "Console" # Console File 
  LogLevel: "Debug" # Debug Info Warn Error

Zookeeper:
  Host: 127.0.0.1
  Port: 2181